// <auto-generated />
namespace IrisMailler.DataModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Content : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Content));
        
        string IMigrationMetadata.Id
        {
            get { return "201302012114477_Content"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
