// <auto-generated />
namespace IrisMailler.DataModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class folderType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(folderType));
        
        string IMigrationMetadata.Id
        {
            get { return "201301131816038_folderType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
