// <auto-generated />
namespace IrisMailler.DataModel.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Content1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Content1));
        
        string IMigrationMetadata.Id
        {
            get { return "201302021136185_Content1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
